version: "3.4"
services:
  beacon-chain:
    image: "beacon-chain.gnosis-beacon-chain-prysm.dnp.dappnode.eth:0.1.0"
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v2.1.4-rc.0
    volumes:
      - "beacon-chain-data:/data"
    ports:
      - 12000/udp
      - 13000/tcp
    restart: unless-stopped
    environment:
      WEB3_BACKUP: "https://rpc.gnosischain.com/"
      HTTP_WEB3PROVIDER: "http://nethermind-xdai.dappnode:8545"
      CORSDOMAIN: "http://gnosis-beacon-chain-prysm.dappnode"
      DEPLOYMENT_BLOCK: 19469077
      EXTRA_OPTS: ""
  validator:
    image: "validator.gnosis-beacon-chain-prysm.dnp.dappnode.eth:0.1.0"
    build:
      context: validator
      args:
        UPSTREAM_VERSION: v2.1.4-rc.0
    volumes:
      - "validator-data:/root/"
    restart: unless-stopped
    environment:
      BEACON_RPC_PROVIDER: "beacon-chain.gnosis-beacon-chain-prysm.dappnode:4000"
      BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.gnosis-beacon-chain-prysm.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
volumes:
  beacon-chain-data: {}
  validator-data: {}
